name: Python

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/60 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python main.py
        env:
          raw_datas: ${{ secrets.RAW_DATA }}
